### ISSUE TITLE
smooth page transition

### ISSUE THREAD

**Issue by junevm** [nylo-core/nylo#120]
I'm striving to achieve iOS-like smooth page transitions in my Flutter app. While the page_transition package provides detailed control over animations through curves, Nylo (built on page_transition) lacks this customization. Is there a way to expose page_transition's curves in Nylo or explore alternative navigation methods to maintain smooth transitions?

Also see: https://stackoverflow.com/questions/56026568/how-to-achieve-ios-like-smooth-page-transition-animation-in-flutter

**Comment by agordn52** [comment]
Hi @a0v0,

You can modify the page transition settings by passing the `pageTransitionSettings` parameter into the `routeTo` helper.
Here's an example.

``` dart
routeTo(HomePage.path, pageTransitionSettings: PageTransitionSettings(
                 duration: Duration(seconds: 1),
                 curve: Curves.easeInOutCubic,
                  alignment: Alignment.topCenter,
                  fullscreenDialog: true,
                  isIos: true,
                  opaque: true,
                  inheritTheme: true,
                  childCurrent: context.widget,
                  context: context,
));
```
Let's continue this discussion in the [discussions](https://github.com/nylo-core/nylo/discussions) tab because it's not necessarily an issue in the Nylo framework but a query, thanks.
