### ISSUE TITLE
Cannot make a model from JSON

### ISSUE THREAD

**Issue by joshua1996** [nylo-core/nylo#150]
![image](https://github.com/nylo-core/nylo/assets/7079972/31a8b7b1-bc4c-4c97-9f2e-78f2840dd654)

in Windows 11, press Ctrl + C, will perform terminate batch job.

**Comment by agordn52** [comment]
Hi @joshua1996,

Thanks for reporting this!
Unfortunately, I don't own a Windows machine, so I cannot provide a quick fix.
I'll close this issue because I won't be able to deal with it swiftly.

If you can solve this, please submit a PR.
I will update the docs on [nylo.dev](nylo.dev) to let people know this feature is only for Mac atm.

**Comment by Im-PJ** [comment]
Solution is to hit enter then Ctrl+Z then hit enter again
